export PUBLIC_URL=https://api.kush.jewelry
export CLOUDINARY_NAME=dxzszsp1e
export CLOUDINARY_KEY=259558775787678
export CLOUDINARY_SECRET=If9FzlhvoIlqaZwixRrQYW0T-H0
export SMTP_HOST=smtp.resend.com
export SMTP_PORT=465
export SMTP_USERNAME=resend
export SMTP_PASSWORD=re_4JrtYSot_8PbZoLo2EUCsZA9uJErKkKH6
export STRIPE_SECRET_KEY=sk_test_51PFDLACbbGEU7nQAtyAQVk3PzI910sjGXzXBRBhRa30yCaYOBtYKF5k5ujLSDeWB86P98Ecg37T913gZDzKV1TpU00f2CwK3Re
export STRIPE_PUBLIC_KEY=pk_test_51PFDLACbbGEU7nQAgiCJ7aEIvKsAVBGKj1rmMNQ6AnadzZHcxMrasJiEshuBaT5Ap8BDUQNqUXR7ecayG7Ed5Nwa00FOpWYdCC
export STRIPE_WEBHOOK_SECRET=whsec_1d1f4c8fbd4e4c50127705f607e7af8a40eac20eccebf6800746e55f73c215ba
export TG_TOKEN=7270632682:AAEs6SuKEWMpMvq6BMGPm-_-uIbHABbrbnQ
export TG_CHAT_ID=-4519315064
export LIQPAY_PUBLIC_KEY=sandbox_i2714471428
export LIQPAY_PRIVATE_KEY=sandbox_YKxKymXMrPDRj8m1pG9wkWdV8tY9YEnAHdg0K9Nk
export TG_TOKEN=7270632682:AAEs6SuKEWMpMvq6BMGPm-_-uIbHABbrbnQ
export TG_CHAT_ID=-4519315064
export TG_CHAT_ORDER_ID=-4516670686
export HOST=0.0.0.0
export PORT=1337
export APP_KEYS=ULtuwhjuD5OXoi5nwhV2Dg==,EN2i6xhaP6wjGc7qKNpA6g==,7cInknxc7IV0n9Aa7hG2mg==,GYNahrUHcRRM7YB4rbyxCA==
export API_TOKEN_SALT=F0zOGwwn0n9x7sB/12eLUA==
export ADMIN_JWT_SECRET=LPKcxBTDPUV+aZH66zDxnA==
export TRANSFER_TOKEN_SALT=Qdu+JfKzNAxlJ/oxH9neGQ==
export JWT_SECRET=Ds16En+G+a+AIOpj2x1Bnw==
export DATABASE_CLIENT=postgres
export DATABASE_HOST="kush-prod.cpoeg2ikgxrl.eu-central-1.rds.amazonaws.com"
export DATABASE_PORT=5432
export DATABASE_NAME=api
export DATABASE_USERNAME=strapi_admin
export DATABASE_PASSWORD="J!|efP|ziUJsZ26E*HdCLAn!V3Q$"
export DATABASE_SSL=false
export RESEND_API_KEY=re_WuJvNbeP_P6SY44xwK9Wp8bj3ZaujkqoE


vars=(
    PUBLIC_URL CLOUDINARY_NAME CLOUDINARY_KEY CLOUDINARY_SECRET SMTP_HOST
    SMTP_PORT SMTP_USERNAME SMTP_PASSWORD STRIPE_SECRET_KEY STRIPE_PUBLIC_KEY
    STRIPE_WEBHOOK_SECRET TG_TOKEN TG_CHAT_ID TG_CHAT_ORDER_ID HOST PORT
    APP_KEYS API_TOKEN_SALT ADMIN_JWT_SECRET TRANSFER_TOKEN_SALT JWT_SECRET
    DATABASE_CLIENT DATABASE_HOST DATABASE_PORT DATABASE_NAME DATABASE_USERNAME
    DATABASE_PASSWORD DATABASE_SSL RESEND_API_KEY
)

# Loop through each variable and store it in Parameter Store
for var in "${vars[@]}"; do
  aws ssm put-parameter \
    --name "/backend/prod/$var" \
    --value "${!var}" \
    --type "String" \
    --overwrite
done
