name: Push
on:
  push:
    paths-ignore:
      - '.github/workflows/*'
jobs:
  test:
    runs-on: self-hosted
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: ./script.sh
        env:
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}